### ISSUE TITLE
Does this work on Jetson Orin nano dev kit?

### ISSUE THREAD

**Issue by rs1990** [defunctzombie/jetson-nano-image-maker#10]
I have an nvidia jetson orin nano with jetpack 6.1 and its configured for a LLM project. Curious if the scripts supports creating images for Jetson Orin boards. 

Thank you

**Comment by defunctzombie** [comment]
I doubt it works out of the box but probably with some changes it could with. If you do find it works or some changes to make it work, I'd love to document that in the readme so others can benefit. Thanks!
