### ISSUE TITLE
Are cuda libraries suppose to be installed?

### ISSUE THREAD

**Issue by Brac24** [defunctzombie/jetson-nano-image-maker#4]
Hello. Thank you for publishing this tool.

Question about the Dockerfile. What are the nvidia-l4t- packages installing? For example nvidia-l4t-cuda. I thought it would be the cuda libraries but I don't see them in the image. Do we install the cuda libraries differently?

Thank you

**Comment by defunctzombie** [comment]
@Brac24 I believe those package install some lower level support items. I don't know from memory but yes my general thinking is that you might need to install the cude libraries separately.

These installation docs might be useful: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#ubuntu
