### ISSUE TITLE
Jetson Nano with EMMC

### ISSUE THREAD

**Issue by sergi0g** [defunctzombie/jetson-nano-image-maker#7]
Hello. I am interested in building my own custom image for Jetson Nano. Your approach looks very convenient. I wanted to ask if it would also work for the Jetson Nano with EMMC, as mine does not have support for sd cards.

**Comment by defunctzombie** [comment]
Don't know but my hunch is it will or it will with some tweaks. Give it a try and if you learn that there are changes you had to make to the scripts etc I'd be happy to include notes in the readme.

**Comment by sergi0g** [comment]
I can flash the image to the nano. I'm just afraid I might brick it.
